name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

        steps:
        - uses: actions/checkout@v1
        - run: npm install
        - run: npm run build
        - run: npm test